services:
  db:
    image: postgres:16-alpine
    container_name: school-app-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: school_app
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/nsu-upprpo/school-backend-image:main
    container_name: school-app-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/school_app
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_H2_CONSOLE_ENABLED: "false"
    ports:
      - "8080:8080"

volumes:
  postgres_data: