# Todo: POSTGRES_USER + POSTGRES_PASSWORD to env file
services:
  db:
    image: postgres:16-alpine
    container_name: school-app-db
    environment:
      POSTGRES_DB: school_app
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: school_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: school-app-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/school_app
      SPRING_DATASOURCE_USERNAME: school_user
      SPRING_DATASOURCE_PASSWORD: school_pass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_H2_CONSOLE_ENABLED: "false"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
